default:
  image: node:14.18.0

deploy_preview:
  stage: deploy
  only:
    - dev
  script:
    - echo $env:VERCEL_TOKEN
    - echo $VERCEL_TOKEN
    - echo VERCEL_TOKEN
    - npm install vercel
    - ./node_modules/.bin/vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - ./node_modules/.bin/vercel build --token=$VERCEL_TOKEN
    - ./node_modules/.bin/vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  #   rules:
  #     - when: manual
  script:
    - npm install vercel
    - ./node_modules/.bin/vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - ./node_modules/.bin/vercel build --prod --token=$VERCEL_TOKEN
    - ./node_modules/.bin/vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
